<?php

namespace App\Controller;

use Cake\ORM\TableRegistry;
use Cake\Event\Event;

class UsersController extends AppController {

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function cadastrar() {

        $usersTable = TableRegistry::get('Users');

        $user = $usersTable->newEntity();

        $this->set('user',$user);
    }

    public function salvar() {

        $usersTable = TableRegistry::get('Users');

        $user = $usersTable->newEntity($this->request->data());

        if($usersTable->save($user)) {
            $this->Flash->set('Usuario cadastrado com sucesso');
    }
    else {
        $this->Flash->set('Erro ao cadastrar o usuario');
    }

        $this->redirect('Users/cadastrar');
    }

    public function login() {


        /*$userTable = TableRegistry::get('Users');

$user = $userTable->newEntity();

$this->set('user',$user);
*/




        if ($this->request->is('post')){

            $user = $this->Auth->identify();

            if ($user) {
                $this->Auth->setUser($user);
                return $this->redirect($this->Auth->redirectUrl());
            }else {
                $this->flash->set('Usuario ou senha invalidos',['element' => 'error']);
            }
        }

    }

    public function logout() {

        return $this->redirect($this->Auth->logout());

    }


}

?>